### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by ncarding** [markhamilton1/Synchronator#10]
I've installed the script via ptinstaller and the first time I ran it I added the Dropbox token as described. I then got an error so I decided that maybe I didn't have the latest Dropbox module installed. So I installed with StaSh (pip install dropbox). Now everytime I run Synchronator I get this error:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/urllib3/util/timeout.py", line 125, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/49872DF7-85BE-45DD-B173-466F37201759/Pythonista3/Documents/add-ons/ptdownloads/Utilities/Synchronator/Synchronator.py", line 425, in <module>
    check_remote(dbx, state)
  File "/private/var/mobile/Containers/Shared/AppGroup/49872DF7-85BE-45DD-B173-466F37201759/Pythonista3/Documents/add-ons/ptdownloads/Utilities/Synchronator/Synchronator.py", line 333, in check_remote
    state.execute_delta(dbx)
  File "/private/var/mobile/Containers/Shared/AppGroup/49872DF7-85BE-45DD-B173-466F37201759/Pythonista3/Documents/add-ons/ptdownloads/Utilities/Synchronator/Synchronator.py", line 174, in execute_delta
    results = dbx.files_list_folder('', True)
  File "/private/var/mobile/Containers/Shared/AppGroup/49872DF7-85BE-45DD-B173-466F37201759/Pythonista3/Documents/site-packages/dropbox/base.py", line 1336, in files_list_folder
    None,
  File "/private/var/mobile/Containers/Shared/AppGroup/49872DF7-85BE-45DD-B173-466F37201759/Pythonista3/Documents/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/private/var/mobile/Containers/Shared/AppGroup/49872DF7-85BE-45DD-B173-466F37201759/Pythonista3/Documents/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/private/var/mobile/Containers/Shared/AppGroup/49872DF7-85BE-45DD-B173-466F37201759/Pythonista3/Documents/site-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 512, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/adapters.py", line 377, in send
    timeout=timeout
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/urllib3/connectionpool.py", line 547, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/urllib3/connectionpool.py", line 303, in _get_timeout
    return Timeout.from_float(timeout)
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/urllib3/util/timeout.py", line 155, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/urllib3/util/timeout.py", line 98, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/var/containers/Bundle/Application/03936604-C3FA-4811-BCC3-447B3BF1604B/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/urllib3/util/timeout.py", line 128, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int or float.

**Comment by jsbain** [comment]
can you type
``` 
import dropbox
import requests
print(dropbox.__version__)
print(requests.__version__)
```

**Comment by ncarding** [comment]
I get:
8.4.0
2.5.1

On 20 Oct 2017, at 02:45, jsbain <notifications@github.com> wrote:

import dropbox import requests print(dropbox.__version__) print(requests.__version__)

**Comment by brian-hodges** [comment]
This is a known issue with python's requests module. The requests library made a mistake in their timeout implementation that wasn't caught until dropbox decided to use that part of the API. If you update the requests module to 2.18.1 or higher it should work fine.

**Comment by ncarding** [comment]
Thank you. How do I upgrade the requests module within Pythonista?


On 25 Oct 2017, at 04:05, brian-hodges <notifications@github.com> wrote:

This is a known issue with python's requests module. The requests library made a mistake in their timeout implementation that wasn't caught until dropbox decided to use that part of the API. If you update the requests module to 2.18.1 or higher it should work fine.
